site_name: Sistema de Recomendación Musical

theme:
  name: material

nav:
  - Home: index.md
  - Manual de Usuario: manual_usuario.md
  - Guía de Despliegue: manual_despliegue.md
  - Ingeniería de Datos: data_engineering.md
  - Modelos de IA: ai_models.md
  - API Backend: backend_api.md
  - Frontend Angular: frontend_angular.md
  - MLOps y Evaluación: mlops_evaluation.md
  - Ayuda MkDocs: help-mkdocs.md


